---
title: Incumbency
author: 'Corine Chung'
date: '2022-10-02'
slug: []
categories: []
tags: []
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

# load libraries
library(tidyverse)
library(ggplot2)
library(dplyr)
library(blogdown)
library(stargazer)
library(readr)
library(lubridate)
library(ggrepel)
library(usmap)
library(janitor)
library(rmapshaper)
library(sf)
library(leaflet)
library(stringr)
library(tigris)

# read in data 
historical <- read_csv("house party vote share by district 1948-2020.csv") %>% 
  clean_names()
expert <- read_csv("expert_rating.csv")
incumbency <- read_csv("incumb_dist_1948-2020.csv")

#subset for district level democratic vote share in 2018
dems_2018 <- historical %>% 
  select(race_year, state, area, dem_votes_major_percent, rep_votes_major_percent, rep_votes, dem_votes, rep_status, dem_status, winner_party) %>% 
  rename("year" = "race_year") %>% 
  filter(year == 2018) %>%
  separate(area, into = c("area", "district"), sep = " ") %>% 
  select(-area) %>% 
  mutate(district = case_when(
    district == "Large" ~ "AL",
    TRUE ~ district
  ))
#reformat single district states 
dems_2018$district[is.na(dem_2018$district)] = 1
dems_2018 <- dems_2018 %>%
   mutate(district = case_when(
    district == "AL" ~ "1",
    TRUE ~ district
  ))
#change class
dems_2018$district <- as.numeric(dems_2018$district)
```

```{r, eval = TRUE, echo = FALSE, warning = FALSE, message= FALSE, Include = FALSE}
cd116 <- congressional_districts(
  state = NULL,
  cb = FALSE,
  resolution = "500k",
  year = 2018)
  
state <- read_csv("us_states.csv")
state <- state %>%
  rename("state" = "st")
district <- cd116 %>%
  left_join(state, by = "state")
  
district2 <- district %>%
  select(-c("state")) %>%
  rename("state" = "stname", "district" = "CD116FP", "st" = "stusps")
district2$district <- as.numeric(district2$district)
district2 <- district2 %>%
  mutate(district = case_when(
    district == 0 ~ 1,
    TRUE ~ district
  ))
#merge data 
alldata <- district2 %>%
  left_join(dem_2018, by = c("state", "district"))
#simplifiy for plot
simpdata <- alldata %>%
  filter(state != "Alaska", state != "Hawaii") %>%
  #rename("st" = "stusps") %>%
  mutate(district = case_when(
    district == 0 ~ 1,
    TRUE ~ district
  )) %>%
  ms_simplify()
simpdata$district <- as.numeric(simpdata$district)
#Plot Dem voteshare by district in 2018
ggplot() + 
  geom_sf(data=simpdata,aes(fill=dem_votes_major_percent),
          inherit.aes=FALSE,alpha=0.9) + 
  scale_fill_gradient(low = "white", high = "dodger blue", limits=c(0,100), name = "Vote Share Percentage") +
  theme_void() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(title = "Democratic Vote Share in 2018 Midterms")
```